# Generated by Django 5.2.10 on 2026-01-30 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "planetarium",
            "0003_alter_ticket_options_alter_ticket_unique_together_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ticket",
            options={"ordering": ["row", "seat", "show_session"]},
        ),
        migrations.AlterField(
            model_name="showtheme",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
