# Generated by Django 5.2.10 on 2026-02-02 17:20

import planetarium.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planetarium", "0004_alter_ticket_options_alter_showtheme_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="astronomyshow",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=planetarium.models.astronomy_show_image_path,
            ),
        ),
    ]
