# Generated by Django 5.2.10 on 2026-02-06 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planetarium", "0005_astronomyshow_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="astronomyshow",
            name="themes",
            field=models.ManyToManyField(
                blank=True, related_name="astronomy_shows", to="planetarium.showtheme"
            ),
        ),
    ]
